# Generated by Django 4.2.13 on 2024-07-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Newborn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dateOfBirth", models.DateField()),
                ("timeOfBirth", models.TimeField()),
                ("birthWeight", models.PositiveIntegerField()),
                ("gender", models.IntegerField()),
                ("fSkinTone", models.IntegerField()),
                ("mSkinTone", models.IntegerField()),
                ("kramer", models.IntegerField()),
                ("jaundice", models.BooleanField()),
                ("bilirubin", models.FloatField()),
                ("foreheads", models.ManyToManyField(to="jaundice_api.imagemodel")),
            ],
        ),
    ]
