# Generated by Django 4.2.13 on 2024-07-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jaundice_api", "0002_alter_imagemodel_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagemodel",
            name="img",
            field=models.ImageField(upload_to=""),
        ),
    ]
